import type { Exercise, WorkoutLog, WorkoutRoutine } from "@/features/workout/types";

export const mockRoutine: WorkoutRoutine = {
  id: "routine-push-legs-pull",
  name: "Push / Legs / Pull",
  daysPerWeek: 4,
  sessions: [
    {
      id: "push",
      name: "Push",
      exerciseIds: ["bench-press", "incline-db-press", "shoulder-press", "triceps-pushdown"],
    },
    {
      id: "legs",
      name: "Legs",
      exerciseIds: ["squat", "romanian-deadlift", "leg-press", "calf-raises"],
    },
    {
      id: "pull",
      name: "Pull",
      exerciseIds: ["pull-up", "barbell-row", "lat-pulldown", "biceps-curl"],
    },
  ],
};

export const mockExercises: Exercise[] = [
  {
    id: "bench-press",
    name: "Bench Press",
    variant: "Barbell",
    setsTarget: 4,
    repsTarget: "6-8",
    restSeconds: 120,
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front deltoid"],
  },
  {
    id: "incline-db-press",
    name: "Incline Press",
    variant: "Dumbbell",
    setsTarget: 3,
    repsTarget: "8-10",
    restSeconds: 90,
    primaryMuscles: ["Upper chest"],
    secondaryMuscles: ["Triceps", "Front deltoid"],
  },
  {
    id: "shoulder-press",
    name: "Shoulder Press",
    variant: "Machine",
    setsTarget: 3,
    repsTarget: "8-12",
    restSeconds: 90,
    primaryMuscles: ["Deltoids"],
    secondaryMuscles: ["Triceps"],
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    variant: "Cable",
    setsTarget: 3,
    repsTarget: "10-12",
    restSeconds: 75,
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Forearm"],
  },
  {
    id: "squat",
    name: "Back Squat",
    variant: "Barbell",
    setsTarget: 4,
    repsTarget: "5-8",
    restSeconds: 150,
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Core"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    variant: "Barbell",
    setsTarget: 3,
    repsTarget: "6-10",
    restSeconds: 120,
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower back"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    variant: "Machine",
    setsTarget: 3,
    repsTarget: "10-12",
    restSeconds: 90,
    primaryMuscles: ["Quads"],
    secondaryMuscles: ["Glutes"],
  },
  {
    id: "calf-raises",
    name: "Calf Raises",
    variant: "Machine",
    setsTarget: 4,
    repsTarget: "12-15",
    restSeconds: 60,
    primaryMuscles: ["Calves"],
    secondaryMuscles: ["Soleus"],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    variant: "Bodyweight",
    setsTarget: 4,
    repsTarget: "6-10",
    restSeconds: 120,
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Core"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    variant: "Barbell",
    setsTarget: 3,
    repsTarget: "8-10",
    restSeconds: 120,
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Lower back"],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    variant: "Cable",
    setsTarget: 3,
    repsTarget: "10-12",
    restSeconds: 90,
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
  },
  {
    id: "biceps-curl",
    name: "Biceps Curl",
    variant: "Dumbbell",
    setsTarget: 3,
    repsTarget: "10-12",
    restSeconds: 75,
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearm"],
  },
];

export const mockLogs: WorkoutLog[] = [
  {
    id: "log-2026-03-03",
    dateISO: "2026-03-03",
    sessionName: "Push",
    durationMinutes: 64,
    notes: "Great energy, increase press by 2.5kg next session.",
    entries: [
      {
        exerciseId: "bench-press",
        performedSets: [
          { reps: 8, loadKg: 60 },
          { reps: 8, loadKg: 60 },
          { reps: 7, loadKg: 62.5 },
          { reps: 6, loadKg: 62.5 },
        ],
      },
      {
        exerciseId: "shoulder-press",
        performedSets: [
          { reps: 10, loadKg: 30 },
          { reps: 9, loadKg: 30 },
          { reps: 8, loadKg: 30 },
        ],
      },
    ],
  },
  {
    id: "log-2026-03-01",
    dateISO: "2026-03-01",
    sessionName: "Legs",
    durationMinutes: 71,
    notes: "Focused on squat technique.",
    entries: [
      {
        exerciseId: "squat",
        performedSets: [
          { reps: 8, loadKg: 80 },
          { reps: 7, loadKg: 82.5 },
          { reps: 7, loadKg: 82.5 },
          { reps: 6, loadKg: 85 },
        ],
      },
      {
        exerciseId: "leg-press",
        performedSets: [
          { reps: 12, loadKg: 160 },
          { reps: 12, loadKg: 160 },
          { reps: 10, loadKg: 170 },
        ],
      },
    ],
  },
];
